name: GPT Frontend + Think Auto Loop

permissions:
  contents: write

on:
  workflow_dispatch:       # manual trigger
  push:                    # on push to main
    branches: [main]
  schedule:                # daily at midnight UTC
    - cron: '0 0 * * *'

jobs:
  optimize-and-think:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 📦 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🧪 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv

      - name: 🤖 Run GPT Rewrite Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/gpt_rewrite_frontend.py

      - name: 🧠 Run GPT Think Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python gpt_think.py

      - name: ✅ Commit and Push Changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GPT_AUTOMATION_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 GPT rewrite & think automation"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
