name: GPT Frontend Optimizer

permissions:
  contents: write

on:
  workflow_dispatch:       # allows manual runs
  push:                    # runs on every push to main
    branches: [main]
  schedule:                # runs daily at midnight UTC
    - cron: '0 0 * * *'

jobs:
  optimize-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv

      - name: Run GPT Rewrite Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/gpt_rewrite_frontend.py

      - name: Commit and push changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 GPT optimization updates"
          git push
